apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: webserver

namespace: oai-demo

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pvc.yaml

configMapgenerator:
  - name: oai-web-content
    files:
      - index.html
